# global settings
seed: 42
logs_dir: './model_logs'
save_interval: 5
sample_interval: 50
run_name: cyclegan

device: cuda:0
num_epochs: 200

# dataset settings
num_workers: 12
dataset_dir: 'data/text_zoom'
lr_img_size: !!python/tuple [32, 128] # hxw
hr_img_size: !!python/tuple [32, 128] # hxw
val_split_complexity: easy
test_split_complexity: medium

# -1 to 1 normalization
norm_means: [0.5, 0.5, 0.5]
norm_stds: [0.5, 0.5, 0.5]

# train settings
batch_size: 32
lr: 0.0002
# ckpt_path: model_logs/cyclegan/checkpoints/epoch-85.pth

model:
  type: CycleGAN
  n_residual_blocks: 9
