# global settings
seed: 42
logs_dir: './model_logs'
sample_interval: 50
run_name: esrgan

device: cuda:0
num_epochs: 100

# dataset settings
num_workers: 0
dataset_dir: 'C:\\Users\\Dymok\\Desktop\\text-rsisr\\data\\text_zoom'
lr_img_size: !!python/tuple [32, 128] # hxw
hr_img_size: !!python/tuple [64, 256] # hxw
val_split_complexity: easy
test_split_complexity: medium

norm_means: [0.0, 0.0, 0.0]
norm_stds: [1.0, 1.0, 1.0]

# train settings
batch_size: 8
lr: 0.0002
# ckpt_path: model_logs\esrgan\checkpoints\epoch-1.pth
model:
  type: ESRGAN
  num_rrdb_blocks: 11
  warmup_iters: 500 # how many iters to train only generator with pixel loss

# schedulers:
  # - # generator's scheduler
  #   type: torch.optim.lr_scheduler.MultiStepLR
  #   milestones: [8, 16, 24, 32]
  #   gamma: 0.5

