# global settings
seed: 42
logs_dir: './mnt/model_logs'
save_interval: 1
sample_interval: 50
run_name: pseudosr_esrgan

device: cuda:0

# dataset settings
num_workers: 14
dataset_dir: 'data/text_zoom'
lr_img_size: !!python/tuple [16, 64] # hxw
hr_img_size: !!python/tuple [32, 128] # hxw
val_split_complexity: easy
test_split_complexity: medium

# normalization
norm_means: [0.0, 0.0, 0.0]
norm_stds: [1.0, 1.0, 1.0]

# training settings
num_epochs: 60
batch_size: 4
lr: 0.0001
lr_milestones: [20, 38, 50, 55]
# ckpt_path: model_logs\pseudosr\checkpoints\epoch-56.pth

model:
  type: PseudoModelESRGAN
  warmup_iters: 500 # how many iters to train only generator with pixel loss
