# global settings
seed: 42
logs_dir: './model_logs'
save_interval: 1
sample_interval: 50
run_name: pseudosr

device: cuda:0

# dataset settings
num_workers: 14
dataset_dir: 'C:\\Users\\Dymok\\Desktop\\text-rsisr\\data\\text_zoom'
lr_img_size: !!python/tuple [16, 64] # hxw
hr_img_size: !!python/tuple [32, 128] # hxw
val_split_complexity: easy
test_split_complexity: medium

# -1 to 1 normalization
norm_means: [0.5, 0.5, 0.5]
norm_stds: [0.5, 0.5, 0.5]

# training settings
num_epochs: 60
batch_size: 16
lr: 0.0001
lr_milestones: [20, 38, 50, 55]
# ckpt_path: model_logs\pseudosr\checkpoints\epoch-2.pth

model:
  type: PseudoModel
